name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      # Install the correct Node.js version
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Generate the snake animation
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: siwanetzu

      # Commit and push the generated snake to the output branch
      - name: Commit the Snake
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Generated snake"
          git push
